# Config file for automatic testing at travis-ci.org
dist: xenial
language: python
env:
  global:
    - COVERALLS_PARALLEL=true
matrix:
  fast_finish: true
  include:
    - name: Python 3.8
      python: 3.8
      env: TOXENV=py38-test
    - name: Docs
      python: 3.8
      env:
        - DOCS="true"
        - secure: "Zk6TJNYNXdRGipJGDyPBo/F2xBXiKowPCx7zZg07gpmQvwjGpCUmOGY3AhY8jbdRqt4I8BjJ9WqO49ofWhn03Gd/kXYUjxljpwoLblK+iRNA1F5SzDoOGUVMTbevMpm95Bx5i8KPYLt4YGW3C5JjceAWXjgQvjD6yuOyEPzTYvmvQazeT6MLEPoU+Nqop4ItAWiD0w1gEfsM1uVNqFkFNwm5t/GnMSqNzAPF5AAxWY418hlSoJ4KNW/+zuWWsopRBZMnKuoxlWq85wd/hw5ZoOSS8VIMKEmL/EGbj5EI73KlwenQGDpthAUry908LDiWT5sQ+3KqAFy/uE1JQhD4ijANmyWQo5hjUpsps4cyfxGG6r1HRUBIfwwfdaGUKvCafk4Zd1vIyZcbknCBh6uLWxOHi+9K1l8v/IxSbsdJ3W9LXlWekZJSGLjBTJLMmNi31YEmaAKLUUaq0fC94pObscsKTv/oh6x8sFBHR9YXiKDBFlTnZedH56qUpemDqTc0IDPIxc94Vd6fZZUZQF+5ev/YY2TRzE3IMgSx0mDm7UwlONnyKOE6EBvNErexKkw7tRlYoQXEAloQOhpdIo6ckoQbCvzlZsLFs54nhFGVB49wyZtbACHZk0S/ef6IjguDCMS0nyXI0hhwrdST7E7u4zJdbeDoHiMYcAF/T3J0A7c="

install:
  # any failure stops the build
  - set -e
  - pip install tox
  - pip freeze
  - printenv
script:
  # any failure stops testing immediately
  - set -e
  - |
    if [[ "${DOCS}" == "true" ]]; then
      source .travis/docs.sh
    else
      tox -e $TOXENV
    fi
  - echo "DONE"
after_success:
  # coveralls is prone to random failures (which would fail the Travis job), so we'll handle those silently
  - if [[ "${TOXENV}" =~ test ]]; then tox -e $(echo "${TOXENV}" | sed s/test/runcmd/) -- coveralls -v || echo "Cannot upload to coveralls"; fi
notifications:
  webhooks: https://coveralls.io/webhook
